# Generated by Django 5.2.7 on 2025-11-08 08:27

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def migrate_existing_zoom_tokens(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    UserProfile = apps.get_model("zerver", "UserProfile")

    for user in UserProfile.objects.all():
        # Only migrate if the old field had a value
        if getattr(user, "zoom_token", None) is not None:
            user.video_call_provider_tokens = {
                "zoom_token": user.zoom_token,
            }
            user.save(update_fields=["video_call_provider_tokens"])


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0759_userprofile_is_imported_stub"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="video_call_provider_tokens",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(migrate_existing_zoom_tokens),
        migrations.RemoveField(
            model_name="userprofile",
            name="zoom_token",
        ),
    ]
