# Generated by Django 5.2.9 on 2026-01-07 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0769_rename_profile_field_twitter_to_x"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realm",
            old_name="giphy_rating",
            new_name="gif_rating",
        ),
    ]
